version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-broker-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_INTERNAL:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka-broker-1:9092,SASL_PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      ZOOKEEPER_SASL_ENABLED: "false"
      #KAFKA_SUPER_USERS: User:admin
      #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_LISTENERS: SASL_PLAINTEXT://kafka-broker-1:9092,SASL_PLAINTEXT_INTERNAL://localhost:19092
      #KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/config/jaas-kafka-server.conf
    volumes:
      - ./config/:/opt/kafka/config/
  kafka-ui-1:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui-1
    ports:
      - "8081:8080"
    depends_on:
      - kafka-broker-1
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      